export const iconIds = [
  'accessibility',
  'addConnection',
  'addHardware',
  'addPrinter',
  'addRemovePrograms',
  'binEmpty',
  'binFull',
  'bmpFile',
  'briefcase',
  'calc',
  'cdDrive',
  'cdPlayer',
  'cdTrack',
  'controlPanel',
  'dateTime',
  'defrag',
  'dialUpNetwork',
  'display',
  'documents',
  'error',
  'globe',
  'hardDrive',
  'helpFile',
  'exchange',
  'explorer',
  'find',
  'findComputer',
  'findMsn',
  'floppyDrive',
  'folderOpen',
  'folderClosed',
  'fonts',
  'fontsShortcut',
  'fontFile',
  'fontTtFile',
  'help',
  'hyperterminal',
  'internet',
  'joystick',
  'keyboard',
  'mediaPlayer',
  'menuArrow',
  'midiFile',
  'modems',
  'mouse',
  'msn',
  'msDos',
  'msFax',
  'msMail',
  'msPaint',
  'multimedia',
  'music',
  'myComputer',
  'network',
  'networkNeighborhood',
  'notepad',
  'notepadDoc',
  'passwords',
  'phoneDialer',
  'power',
  'printers',
  'printersShortcut',
  'program',
  'programs',
  'quickView',
  'regionalSettings',
  'question',
  'register',
  'run',
  'scandisk',
  'settings',
  'shutdown',
  'sound',
  'sounds',
  'soundOff',
  'system',
  'taskbar',
  'tree',
  'video',
  'videoFile',
  'volume',
  'warning',
  'waveFile',
  'windowsLogo',
  'wordpad',
  'wordpadDoc',
] as const;

export type IconId = typeof iconIds[number];

export const iconSizes = [8, 16, 24, 32] as const;

export type IconSize = typeof iconSizes[number];

export type IconUrls = Partial<{ [key in IconSize]: string }>;

export type IconList = { [key in IconId]: IconUrls };
